CREATE SEQUENCE BLOCKEDSITE_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;
CREATE SEQUENCE COM_USE_INFO_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;
CREATE SEQUENCE FOOD_TYPE_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;
CREATE SEQUENCE GAME_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;
CREATE SEQUENCE GAME_TYPE_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;
CREATE SEQUENCE GAME_USAGE_INFO_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;
CREATE SEQUENCE LIMITED_AGE_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;
CREATE SEQUENCE PAY_INFO_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;

CREATE SEQUENCE POINT_INFO_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;
CREATE SEQUENCE SETTLE_ACCOUNT_INFO_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;
CREATE SEQUENCE USER_BLACKLIST_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;
CREATE SEQUENCE USER_POINT_INFO_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;
CREATE SEQUENCE WAGE_ACCU_INFO_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;
CREATE SEQUENCE WAGE_INFO_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;
CREATE SEQUENCE WORK_INFO_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;
CREATE SEQUENCE EMPLOYEES_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;

CREATE SEQUENCE USER_NUM_SEQ INCREMENT BY 1 START WITH 0 MINVALUE 0;